name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-bibtex-extra biber

      - name: Compile LaTeX to PDF
        run: |
          xelatex -interaction=nonstopmode main.tex || true
          biber main || true
          xelatex -interaction=nonstopmode main.tex || true
          xelatex -interaction=nonstopmode main.tex || true
          ls -lh main.pdf