name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write  # required for artifact upload in v4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra texlive-bibtex-extra biber

      - name: Compile LaTeX to PDF
        run: |
          xelatex -interaction=nonstopmode main.tex || true
          biber main || true
          xelatex -interaction=nonstopmode main.tex || true
          xelatex -interaction=nonstopmode main.tex || true
          ls -lh main.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf